### ISSUE TITLE
Possible mismatch in comparison operator on closed right interval

### ISSUE THREAD

**Issue by neeshjaa** [neeshjaa/lpm_discretize#2]
In discretize.py, line 114, the comparison operator used to determine whether a value is within one of the discrete intervals is less-than:
`              if value < cutoff:`
but the intervals returned by polars.qcut() are closed on the right, so it seems like the comparison should be less-than-or-equals:
`              if value <= cutoff:`

This change allows test_get_quantile_based_discretization_function_skewed (plus 77 others) to succeed, but 10 of these fail because of difference in the generated/expected dataframes. My guess is that this has to do with edge cases where values fall precisely on the interval upper bound. But I don't want to hack those changes to the tests until I've had feedback on the change in the comparison.

**Comment by Schaechtle** [comment]
I looked at the tests you fixed -- you are absolutely correct!
